---
title: "Untitled"
author: "Trần Thúy"
date: "`r Sys.Date()`"
output: word_document
---
```{r}
library(dplyr)
library(readxl)
Data <- readxl::read_excel("D:/NEU/TOKT/Bắt buộc/Đề án/Data - Copula.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))

Data <- na.omit(Data)
attach(Data)
returns <- Data %>% dplyr::select (rBVH,rBMI,rCTG)
Prices <- Data %>% dplyr::select (pBVH,pBMI,pCTG)
```
```{r}

library(ggplot2)


ggplot(data = data.frame(returns), aes(x = returns$rBVH)) +
  geom_histogram( fill = "green", color = "blue", alpha = 0.7) +
  labs(title = "Histogram of BVH", x = "Return", y = "Frequency") +
  theme_minimal()

ggplot(data = data.frame(returns), aes(x = returns$rBMI)) +
  geom_histogram( fill = "green", color = "blue", alpha = 0.7) +
  labs(title = "Histogram of BMI", x = "Return", y = "Frequency") +
  theme_minimal()

ggplot(data = data.frame(returns), aes(x = returns$rCTG)) +
  geom_histogram( fill = "green", color = "blue", alpha = 0.7) +
  labs(title = "Histogram of CTG", x = "Return", y = "Frequency") +
  theme_minimal()
```

```{r}
library(rugarch)
# B1: Ước lượng GARCH(1,1)-t và lấy phần dư chuẩn hóa 
spec_garch <- ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1,1)),
                         mean.model = list(armaOrder = c(0,0)),
                         distribution.model = "std")  # Student-t

std_residuals <- matrix(NA, nrow = nrow(returns), ncol = ncol(returns))

for (i in 1:ncol(returns)) {
  returns_col <- returns[[i]]  
  returns_col <- as.numeric(returns_col)
  
  fit <- ugarchfit(spec = spec_garch, data = returns_col)
  std_residuals[, i] <- residuals(fit, standardize = TRUE)
}

head (std_residuals,5)
```
```{r}
library(MASS)
#B2: Chuyển phần dư sang uniform qua phân phối Student-t 
fit_marginals <- lapply(1:3, function(i) {
  fitdistr(std_residuals[, i], "t")
})

```

```{r}
library(tidyr)
# Tạo CDF
u_data <- matrix(NA, nrow = nrow(std_residuals), ncol = 3)
for (i in 1:3) {
  m <- fit_marginals[[i]]$estimate["m"]
  s <- fit_marginals[[i]]$estimate["s"]
  df <- fit_marginals[[i]]$estimate["df"]
  u_data[, i] <- pt((std_residuals[, i] - m)/s, df = df)
}

head(u_data,5)

#CDF
u_data_long <- as.data.frame(u_data)
colnames(u_data_long) <- c("u1", "u2", "u3")
u_data_long$id <- 1:nrow(u_data_long)
u_data_long <- gather(u_data_long, key = "variable", value = "value", -id)

ggplot(u_data_long, aes(x = value, color = variable)) +
  stat_ecdf(geom = "step") +
  labs(title = "CDF of Standardized Residuals",
       x = "Standardized Residuals",
       y = "CDF") +
  theme_minimal()
```



```{r}
library(copula)
#B3: Fit t-Copula
cop_model <- tCopula(dim = 3, df = 4, dispstr = "un")
fit_copula <- fitCopula(cop_model, data = u_data, method = "ml")

```
```{r}
#B4: Mô phỏng từ copula
set.seed(1)
n_sim <- 100000
sim_u <- rCopula(n_sim, fit_copula@copula)

head (sim_u,5)
```
```{r}
#B5: Biến đổi ngược từ U về phần dư chuẩn hóa
sim_z <- matrix(NA, nrow = n_sim, ncol = 3)
for (i in 1:3) {
  m <- fit_marginals[[i]]$estimate["m"]
  s <- fit_marginals[[i]]$estimate["s"]
  df <- fit_marginals[[i]]$estimate["df"]
  sim_z[, i] <- qt(sim_u[, i], df = df) * s + m
}

head(sim_z,5)
```

```{r}
#B6: Biến đổi phần dư chuẩn hóa về lợi suất mô phỏng 
sim_returns <- matrix(NA, nrow = n_sim, ncol = 3)

for (i in 1:3) {
  returns_col <- as.numeric(returns[[i]])  
  fit <- ugarchfit(spec = spec_garch, data = returns_col)
  sigma_last <- tail(sigma(fit), 1) 
  mu <- fitted(fit)[nrow(fitted(fit))]  
  sigma_last_vector <- rep(sigma_last, n_sim)
  mu_vector <- rep(mu, n_sim)
  sim_returns[, i] <- mu_vector + sim_z[, i] * sigma_last_vector
}

head(sim_returns,5)
```
```{r}
sim_returns_df <- data.frame(sim_returns)

colnames(sim_returns_df) <- paste("Cổ phiếu", 1:3)
sim_returns_long <- reshape2::melt(sim_returns_df, variable.name = "Cổ phiếu", value.name = "Lợi suất")

ggplot(sim_returns_long, aes(x = `Lợi suất`)) + 
  geom_histogram( bins=50,fill = "skyblue", color = "black", alpha = 0.7) +
  facet_wrap(~ `Cổ phiếu`, scales = "free") +
  labs(title = "Biểu đồ lợi suất mô phỏng", x = "Lợi suất", y = "Tần suất") +
  xlim(-10, 10)+
  theme_minimal()

```

```{r}
weights <- c(1/3, 1/3, 1/3)
portfolio_returns <- sim_returns %*% weights

VaR_95 <- -quantile(portfolio_returns, probs = 0.05)
VaR_99 <- -quantile(portfolio_returns, probs = 0.01)
cat("VaR 95% =", VaR_95, "\n")
cat("VaR 99% =", VaR_99, "\n")
```

